from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from zero_os.capability_expansion_protocol import capability_expansion_protocol_status


_STAGE_FILE_MAP = {
    "target_definition": ("README.md",),
    "intent_parser": ("intent.py",),
    "typed_plan_steps": ("planner.py",),
    "contradiction_checks": ("contradiction.py",),
    "execution_contract": ("executor.py",),
    "rollback_and_audit": ("audit.py",),
    "tests_and_pressure": ("tests",),
    "controller_surface": ("controller.json",),
}


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _assistant_dir(cwd: str) -> Path:
    path = Path(cwd).resolve() / ".zero_os" / "assistant"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _factory_path(cwd: str) -> Path:
    return _assistant_dir(cwd) / "domain_pack_factory.json"


def _domain_pack_root(cwd: str) -> Path:
    path = Path(cwd).resolve() / ".zero_os" / "domain_packs"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _save(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _load(path: Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return default


def _normalize_domain_key(name: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_")
    return normalized or "new_domain"


def _manifest_path(cwd: str, domain_key: str) -> Path:
    return _domain_pack_root(cwd) / domain_key / "domain_pack.json"


def _domain_dir(cwd: str, domain_key: str) -> Path:
    return _domain_pack_root(cwd) / domain_key


def _write_if_missing(path: Path, content: str) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _manifest_for(domain_key: str, protocol: dict) -> dict:
    return {
        "schema_version": 1,
        "domain_key": domain_key,
        "label": domain_key.replace("_", " ").title(),
        "created_utc": _utc_now(),
        "status": "scaffolded",
        "required_contracts": [item["stage"] for item in protocol.get("required_contracts", [])],
        "stages": {item["stage"]: "stub" for item in protocol.get("required_contracts", [])},
        "admission_ready": False,
        "notes": "Generated by the Zero AI domain-pack factory. Fill the stubs, then run verify.",
    }


def _feature_request_metadata(request: str) -> dict:
    text = str(request or "").strip()
    lowered = text.lower()
    label = text or "New feature domain"
    domain_key = _normalize_domain_key(text)
    focus = "observe"
    if any(token in lowered for token in ("send", "post", "write", "create", "add", "update", "execute", "run")):
        focus = "act"
    elif any(token in lowered for token in ("status", "inspect", "scan", "find", "analyze", "review")):
        focus = "observe"
    if any(token in lowered for token in ("calendar", "time", "schedule", "reminder")):
        subsystem = "calendar_time"
    elif any(token in lowered for token in ("message", "email", "reply", "draft", "communications", "send")):
        subsystem = "communications"
    elif any(token in lowered for token in ("browser", "web", "http://", "https://", "api", "github")):
        subsystem = "integration"
    elif any(token in lowered for token in ("bug", "error", "virus", "contradiction", "workspace", "scan")):
        subsystem = "observation"
    else:
        subsystem = domain_key
    return {
        "request": text,
        "domain_key": domain_key,
        "label": domain_key.replace("_", " ").title(),
        "focus": focus,
        "subsystem": subsystem,
        "target_summary": text or "Define the real user target.",
    }


def _generate_readme(meta: dict) -> str:
    return (
        f"# {meta['label']}\n\n"
        "Target:\n"
        f"- {meta['target_summary']}\n\n"
        "Non-goals:\n"
        "- Do not bypass contradiction checks.\n"
        "- Do not bypass approval gates for high-risk actions.\n"
        "- Do not mutate identity-core or unrestricted control paths.\n"
    )


def _generate_intent(meta: dict) -> str:
    return (
        "from __future__ import annotations\n\n"
        "def extract_domain_intent(request: str) -> dict:\n"
        "    text = request.strip()\n"
        "    lowered = text.lower()\n"
        f"    focus = {meta['focus']!r}\n"
        "    entities = {}\n"
        "    if 'http://' in lowered or 'https://' in lowered:\n"
        "        entities['url'] = text\n"
        "    return {\n"
        f"        'intent': focus,\n"
        "        'goal': text,\n"
        "        'claims': [],\n"
        "        'constraints': {},\n"
        "        'entities': entities,\n"
        "    }\n"
    )


def _generate_planner(meta: dict) -> str:
    default_kind = "observe" if meta["focus"] == "observe" else "prepare_action"
    return (
        "from __future__ import annotations\n\n"
        "def build_domain_steps(request: str) -> list[dict]:\n"
        "    text = request.strip()\n"
        "    steps = []\n"
        f"    steps.append({{'kind': '{default_kind}', 'target': text}})\n"
        "    if 'status' in text.lower() or 'inspect' in text.lower():\n"
        "        steps.insert(0, {'kind': 'observe', 'target': text})\n"
        "    return steps\n"
    )


def _generate_executor(meta: dict) -> str:
    return (
        "from __future__ import annotations\n\n"
        "def execute_domain_step(step: dict) -> dict:\n"
        "    kind = step.get('kind', 'observe')\n"
        "    target = step.get('target')\n"
        "    return {\n"
        "        'ok': True,\n"
        "        'kind': kind,\n"
        "        'target': target,\n"
        f"        'domain': {meta['domain_key']!r},\n"
        "        'summary': f'{kind} prepared for {target}',\n"
        "    }\n"
    )


def _generate_contradiction(meta: dict) -> str:
    return (
        "from __future__ import annotations\n\n"
        "def review_domain_branch(plan: dict) -> list[dict]:\n"
        "    issues = []\n"
        "    steps = list(plan.get('steps', []))\n"
        "    if not steps:\n"
        "        issues.append({'kind': 'missing_steps', 'reason': 'domain plan has no steps'})\n"
        "    return issues\n"
    )


def _generate_audit(meta: dict) -> str:
    return (
        "from __future__ import annotations\n\n"
        "def audit_domain_event(action: str, payload: dict) -> dict:\n"
        "    return {\n"
        "        'ok': True,\n"
        "        'action': action,\n"
        "        'payload': dict(payload),\n"
        f"        'domain': {meta['domain_key']!r},\n"
        "    }\n"
    )


def _generate_controller(meta: dict) -> dict:
    return {
        "commands": [
            f"zero ai {meta['domain_key']} status",
            f"zero ai {meta['domain_key']} refresh",
        ],
        "capability_key": f"{meta['domain_key']}_domain_pack",
        "subsystem": meta["subsystem"],
        "generated_from_request": meta["request"],
    }


def _generate_test(meta: dict) -> str:
    return (
        "from pathlib import Path\n\n"
        "def test_domain_pack_generated_contract_files_exist() -> None:\n"
        "    domain_dir = Path(__file__).resolve().parents[1]\n"
        "    assert (domain_dir / 'intent.py').exists()\n"
        "    assert (domain_dir / 'planner.py').exists()\n"
        "    assert (domain_dir / 'executor.py').exists()\n"
        "    assert (domain_dir / 'contradiction.py').exists()\n"
        "    assert (domain_dir / 'audit.py').exists()\n"
    )


def domain_pack_scaffold(cwd: str, name: str) -> dict:
    protocol = capability_expansion_protocol_status(cwd)
    domain_key = _normalize_domain_key(name)
    domain_dir = _domain_dir(cwd, domain_key)
    manifest = _manifest_for(domain_key, protocol)

    _write_if_missing(
        domain_dir / "README.md",
        (
            f"# {manifest['label']}\n\n"
            "Target:\n"
            "- Define the real user target.\n\n"
            "Non-goals:\n"
            "- State what this domain must not do.\n"
        ),
    )
    _write_if_missing(
        domain_dir / "intent.py",
        (
            "from __future__ import annotations\n\n"
            "def extract_domain_intent(request: str) -> dict:\n"
            "    return {\n"
            "        'intent': 'observe',\n"
            "        'goal': request.strip(),\n"
            "        'claims': [],\n"
            "        'constraints': {},\n"
            "    }\n"
        ),
    )
    _write_if_missing(
        domain_dir / "planner.py",
        (
            "from __future__ import annotations\n\n"
            "def build_domain_steps(request: str) -> list[dict]:\n"
            "    return [{'kind': 'observe', 'target': request.strip()}]\n"
        ),
    )
    _write_if_missing(
        domain_dir / "executor.py",
        (
            "from __future__ import annotations\n\n"
            "def execute_domain_step(step: dict) -> dict:\n"
            "    return {'ok': True, 'kind': step.get('kind', 'observe'), 'target': step.get('target')}\n"
        ),
    )
    _write_if_missing(
        domain_dir / "contradiction.py",
        (
            "from __future__ import annotations\n\n"
            "def review_domain_branch(plan: dict) -> list[dict]:\n"
            "    return []\n"
        ),
    )
    _write_if_missing(
        domain_dir / "audit.py",
        (
            "from __future__ import annotations\n\n"
            "def audit_domain_event(action: str, payload: dict) -> dict:\n"
            "    return {'ok': True, 'action': action, 'payload': dict(payload)}\n"
        ),
    )
    _write_if_missing(
        domain_dir / "controller.json",
        json.dumps(
            {
                "commands": [
                    f"zero ai {domain_key} status",
                    f"zero ai {domain_key} refresh",
                ],
                "capability_key": f"{domain_key}_domain_pack",
                "subsystem": domain_key,
            },
            indent=2,
        )
        + "\n",
    )
    _write_if_missing(
        domain_dir / "tests" / f"test_{domain_key}_domain.py",
        (
            "def test_domain_pack_scaffold_exists() -> None:\n"
            "    assert True\n"
        ),
    )

    manifest_path = _manifest_path(cwd, domain_key)
    _save(manifest_path, manifest)
    verified = domain_pack_verify(cwd, domain_key)
    status = domain_pack_factory_status(cwd)
    return {
        "ok": True,
        "domain_key": domain_key,
        "path": str(domain_dir),
        "manifest_path": str(manifest_path),
        "verify": verified,
        "factory_summary": status.get("summary", {}),
    }


def domain_pack_generate_feature(cwd: str, request: str) -> dict:
    protocol = capability_expansion_protocol_status(cwd)
    meta = _feature_request_metadata(request)
    domain_key = meta["domain_key"]
    domain_dir = _domain_dir(cwd, domain_key)
    manifest = _manifest_for(domain_key, protocol)
    manifest["status"] = "generated"
    manifest["generated_by"] = "zero_ai"
    manifest["feature_request"] = meta["request"]
    manifest["subsystem"] = meta["subsystem"]
    manifest["notes"] = "Generated by Zero AI from a feature request. Verify before admission."

    _write_if_missing(domain_dir / "README.md", _generate_readme(meta))
    _write_if_missing(domain_dir / "intent.py", _generate_intent(meta))
    _write_if_missing(domain_dir / "planner.py", _generate_planner(meta))
    _write_if_missing(domain_dir / "executor.py", _generate_executor(meta))
    _write_if_missing(domain_dir / "contradiction.py", _generate_contradiction(meta))
    _write_if_missing(domain_dir / "audit.py", _generate_audit(meta))
    _write_if_missing(
        domain_dir / "controller.json",
        json.dumps(_generate_controller(meta), indent=2) + "\n",
    )
    _write_if_missing(domain_dir / "tests" / f"test_{domain_key}_domain.py", _generate_test(meta))

    manifest_path = _manifest_path(cwd, domain_key)
    _save(manifest_path, manifest)
    verified = domain_pack_verify(cwd, domain_key)
    status = domain_pack_factory_status(cwd)
    return {
        "ok": True,
        "generated_by": "zero_ai",
        "auto_generated": True,
        "feature_request": meta["request"],
        "domain_key": domain_key,
        "path": str(domain_dir),
        "manifest_path": str(manifest_path),
        "verify": verified,
        "factory_summary": status.get("summary", {}),
    }


def _stage_present(domain_dir: Path, stage: str) -> bool:
    required = _STAGE_FILE_MAP.get(stage, ())
    if not required:
        return False
    for relative in required:
        if (domain_dir / relative).exists():
            return True
    return False


def domain_pack_verify(cwd: str, name: str) -> dict:
    protocol = capability_expansion_protocol_status(cwd)
    domain_key = _normalize_domain_key(name)
    domain_dir = _domain_dir(cwd, domain_key)
    manifest_path = _manifest_path(cwd, domain_key)
    manifest = _load(manifest_path, {})
    required_contracts = [item["stage"] for item in protocol.get("required_contracts", [])]

    issues: list[str] = []
    stage_results: dict[str, dict] = {}
    for stage in required_contracts:
        present = _stage_present(domain_dir, stage)
        stage_results[stage] = {"present": present, "required": True}
        if not present:
            issues.append(stage)

    ready = bool(manifest) and not issues
    if manifest:
        manifest["last_verified_utc"] = _utc_now()
        manifest["admission_ready"] = ready
        manifest["status"] = "ready" if ready else "incomplete"
        manifest["stages"] = {stage: ("ready" if stage_results[stage]["present"] else "missing") for stage in required_contracts}
        _save(manifest_path, manifest)

    status = domain_pack_factory_status(cwd)
    return {
        "ok": True,
        "domain_key": domain_key,
        "path": str(domain_dir),
        "manifest_path": str(manifest_path),
        "admission_ready": ready,
        "missing_stages": issues,
        "stage_results": stage_results,
        "factory_summary": status.get("summary", {}),
    }


def domain_pack_factory_status(cwd: str) -> dict:
    protocol = capability_expansion_protocol_status(cwd)
    packs: list[dict] = []
    ready_count = 0
    scaffolded_count = 0
    for domain_dir in sorted(_domain_pack_root(cwd).iterdir()):
        if not domain_dir.is_dir():
            continue
        manifest = _load(domain_dir / "domain_pack.json", {})
        if not manifest:
            continue
        ready = bool(manifest.get("admission_ready", False))
        if ready:
            ready_count += 1
        else:
            scaffolded_count += 1
        packs.append(
            {
                "domain_key": str(manifest.get("domain_key", domain_dir.name)),
                "label": str(manifest.get("label", domain_dir.name)),
                "status": str(manifest.get("status", "unknown")),
                "admission_ready": ready,
                "path": str(domain_dir),
                "last_verified_utc": str(manifest.get("last_verified_utc", "")),
            }
        )

    payload = {
        "ok": True,
        "time_utc": _utc_now(),
        "path": str(_factory_path(cwd)),
        "root": str(_domain_pack_root(cwd)),
        "summary": {
            "domain_pack_count": len(packs),
            "ready_count": ready_count,
            "scaffolded_count": scaffolded_count,
            "required_contract_count": len(protocol.get("required_contracts", [])),
        },
        "packs": packs,
        "current_priority": [
            "Scaffold new domains through the factory instead of hand-wiring them.",
            "Verify every domain pack against the protocol before admitting it.",
            "Use the factory to ship research, communications, and calendar_time next.",
        ],
    }
    _save(_factory_path(cwd), payload)
    return payload
